apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: check-image
spec:
  validationFailureAction: Enforce
  background: false
  webhookTimeoutSeconds: 30
  failurePolicy: Fail
  rules:
    - name: check-image
      match:
        any:
        - resources:
            kinds:
              - Pod
      verifyImages:
      - imageReferences: 
        - "ghcr.io/shivaswaroop40/containerimages/*"
        mutateDigest: true
        attestors:
        - entries:
          - keys:
              secret:
                name: cosign-public-key
                namespace: kyverno
        imageRegistryCredentials:
          secrets: 
          - ghcr-secret