apiVersion: v1
kind: Pod
metadata:
  name: unsigned-image-pod
spec:
  containers:
    - name: unsigned-container
      image: ghcr.io/shivaswaroop40/containerimages/my-unsigned-image:sha-b3666ac
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
  imagePullSecrets:
    - name: ghcr-secret
