apiVersion: v1
kind: Pod
metadata:
  name: unsigned-image-pod
  labels:
    app: unsigned-app
    security: unsigned
spec:
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 3000
    fsGroup: 3000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - name: unsigned-container
      image: ghcr.io/shivaswaroop40/containerimages/unsigned:sha-16589e8
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 3000
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
          ephemeral-storage: 256Mi
        limits:
          cpu: 200m
          memory: 256Mi
          ephemeral-storage: 512Mi
      ports:
        - containerPort: 8080
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
        initialDelaySeconds: 30
        periodSeconds: 10
      readinessProbe:
        httpGet:
          path: /ready
          port: 8080
        initialDelaySeconds: 5
        periodSeconds: 5
  imagePullSecrets:
    - name: ghcr-secret
