name: Build Image using Containerfile
on: 
  workflow_dispatch:

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v3.8.0

    - name: login to ghcr
      uses: docker/login-action@v3.3.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: build and push OCI image
      uses: docker/build-push-action@v6.10.0
      with:
          push: true
          tags: ghcr.io/shivaswaroop40/containerimages/my-unsigned-image:v1
